export const projects = [
  {
    title: 'Marketplace (Online Course Platform)',
    description: "An upgrade to traditional platforms such as Udemy, coursera with a web3 view while Integraing it with existing web2 platforms.",
      image: '/images/1.png',
      tags: ['web3js', 'Truffle', 'Next js', 'Tailwind CSS','Solidity'],
    source: 'https://github.com/Jayakumar2812/marketplace1-jk',
    visit: 'https://marketplace1-jk.vercel.app/marketplace',
    id: 0,
  },
  {
    title: 'NFT Marketplace',
    description:"A fully functional NFT Marketplace with all the basic features and an creator dashboard deployed on the polygon testnet.",
    image: '/images/2.png',
    tags: ['Nextjs ', 'solidity ', "Tailwind CSS ", "Hardhat ", "ether js"],
    source: 'https://github.com/Jayakumar2812/NFT-Marketplace',
    visit: 'https://nft-marketplace-testnet.vercel.app/',
    id: 1,
  },
  {
    title: 'Proof Of Stake Blockchain',
    description: "P2P connection established, Nodes automatically sync with each other when a transaction is posted. Implemented Block validation, Signature Validation, Transaction Validation and POS consensus protocol. Created API endpoints for Blockchain state, Info , Transaction pool and Transaction.",
      image: '/images/3.png',
      tags: ['Python'],
    source: 'https://github.com/Jayakumar2812/Proof-Of-Stake-Prototype',
    visit: 'https://github.com/Jayakumar2812/Proof-Of-Stake-Prototype',
    id: 2,
  },
  {
    title: 'On-chain Generative NFT',
    description: "Built algorithms for generating svg's which are placed inside the smart contract, that are interpreted off-chain to present the pictures or diagrams generated by algorithms. This method provides solid security at the cost of gas fees.",
    image: '/images/4.png',
    tags: ['Solidity'],
    source: 'https://github.com/Jayakumar2812/onchaingenerative/tree/master',
    visit: 'https://github.com/Jayakumar2812/onchaingenerative/tree/master',
    id: 3,
  },
];

export const TimeLineData = [
  { year: "2022(Current)", text: 'Blockchain Developer at Guardian Link .', },
  { year: "2022(Current)", text: 'Blockchain Developer at D-Frame (Part-Time) .', },
  { year: "2022(Current)", text: 'Freelancing as Blockchain Developer/Consultant .', },
  { year: "2021(3mons)", text: 'Blockchain Developer Intern at Blockchain App Factory .', },
  { year: "2021(1mon)",  text: 'Blockchain Developer Intern at Bytex .', },

];

export const certi = [
  { name: "Blockchain Fundamentals", provider: 'IIT- KHARAGPUR'},
  { name: "De-Fi Specialization", provider: 'Duke University(Coursera)', },
  { name: "BEC vantage[2020]", provider: 'Cambridge University', },
];
